name: publish storybook and npm package
on:
  push:
    branches: "*"
jobs:
  # quality:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: "npm"
  #     - run: npm ci
  #     - run: npm test
  publish-npm:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: quality
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - uses: "phips28/gh-action-bump-version@master"
        with:
          minor-wording: "add,Adds,new"
          major-wording: "MAJOR,cut-major"
          patch-wording: "patch,fixes"
          rc-wording: "RELEASE,alpha"
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_ACCESS_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.SKELETON_COMPONENT_WORKFLOW_GITHUB_TOKEN }}
  publish-storybook:
    runs-on: ubuntu-latest
    # if: ${{ github.ref == 'refs/heads/master' }}
    # needs: quality
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build-storybook
      - run: npx gh-pages -d storybook-static"
        env:
          GITHUB_TOKEN: ${{ secrets.SKELETON_COMPONENT_WORKFLOW_GITHUB_TOKEN }}
